require "core.options"
require "core.remap"
require "plugins.alpha"
-- require "plugins.blink-cmp"
require "plugins.bufferline"
-- require "plugins.codecompanion"
require "plugins.cmp"
require "plugins.colorscheme"
require "plugins.gitsigns"
require "plugins.leap"
require "plugins.lsp"
require "plugins.lualine"
require "plugins.neoscroll"
require "plugins.neotree"
require "plugins.render-markdown"
require "plugins.telescope"
require "plugins.treesitter"

